server:
  port: 8081

spring:
  application:
    name: grpc-server
  cloud:
    consul:
      discovery:
        port: 8500
        hostname: 127.0.0.1

grpc:
  server:
    port: 9090
#  enabled: true
#  inProcessServerName: user