// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/zzsz/user.proto

package com.zzsz.demo;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zzsz.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
