// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/zzsz/user.proto

package com.zzsz.demo;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zzsz.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 3;</code>
   */
  int getAge();
}
